name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r api/requirements.txt

      - name: Build Python API Executable
        run: |
          cd api
          pyinstaller --onefile --name api main.py
          cd ..
          # Create dist directory if it doesn't exist
          mkdir -p dist
          # On macOS, copy without .exe extension
          cp api/dist/api dist/api
          # Make the file executable
          chmod +x dist/api

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Build macOS App
        run: |
          npm run make

      - name: Create ZIP Archive
        run: |
          cd out
          zip -r image-ranker-darwin-x64.zip make/zip/darwin/x64/image-ranker-darwin-x64
          cd ..

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: out/image-ranker-darwin-x64.zip
          if-no-files-found: error
