name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r api/requirements.txt

      - name: Build Python API Executable
        run: |
          cd api
          pyinstaller --onefile --name api main.py
          mkdir -p ../dist/api
          copy dist\api.exe ..\dist\api\
          cd ..

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Build Windows App
        run: |
          npm run make

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            out/make/squirrel.windows/x64/*.exe
            out/make/zip/win32/x64/*.zip
          if-no-files-found: error
